version: '3.4'

services:
  metric.api:
   container_name: metric-api
   ports:
    - 5010:80 
  
  prometheus:
   container_name: prometheus
   ports:
    - 9090:9090 
   volumes: 
    - ./prometheus.yml:/etc/prometheus/prometheus.yml 