scrape_configs:
    
  - job_name: prometheus
    static_configs:
    - targets: ['localhost:9090']
  
  - job_name: metric-api
    scrape_interval: 3s #3 saniyede 1 veriyi topla
    static_configs:
     - targets: ['metric.api:80']