global using Microsoft.Extensions.Hosting;
global using Serilog;
global using Serilog.Exceptions;
global using Serilog.Formatting.Elasticsearch;
global using Serilog.Sinks.Elasticsearch;
global using System.Diagnostics;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;